cargo-features = ["edition2024"]

[package]
name = "sliding_features"
version = "7.0.2"
authors = ["MathisWellmann <wellmannmathis@gmail.com>"]
edition = "2024"
license-file = "LICENSE"
description = "Modular sliding window with various signal processing functions and technical indicators"
repository = "https://github.com/MathisWellmann/sliding_features-rs"
readme = "README.md"
keywords = [
  "sliding-window",
  "signal-processing",
  "modular",
  "technical-analysis",
  "indicators",
]
categories = ["algorithms", "mathematics"]
exclude = ["img/"]

[dependencies]
getset = "0.1"
num = "0.4"

[dev-dependencies]
time_series_generator = "0.4.1"
rand = "0.9"
round = "0.1"
plotters = "0.3"
criterion = "0.7"

[[bench]]
name = "alma"
harness = false

[[bench]]
name = "center_of_gravity"
harness = false

[[bench]]
name = "correlation_trend_indicator"
harness = false

[[bench]]
name = "cumulative"
harness = false

[[bench]]
name = "cyber_cycle"
harness = false

[[bench]]
name = "ehlers_fisher_transform"
harness = false

[[bench]]
name = "ema"
harness = false

[[bench]]
name = "hl_normalizer"
harness = false

[[bench]]
name = "laguerre_filter"
harness = false

[[bench]]
name = "laguerre_rsi"
harness = false

[[bench]]
name = "my_rsi"
harness = false

[[bench]]
name = "noise_elimination_technology"
harness = false

[[bench]]
name = "polarized_fractal_efficiency"
harness = false

[[bench]]
name = "re_flex"
harness = false

[[bench]]
name = "roc"
harness = false

[[bench]]
name = "roofing_filter"
harness = false

[[bench]]
name = "rsi"
harness = false

[[bench]]
name = "sma"
harness = false

[[bench]]
name = "super_smoother"
harness = false

[[bench]]
name = "trend_flex"
harness = false

[[bench]]
name = "vst"
harness = false

[[bench]]
name = "vsct"
harness = false

[[bench]]
name = "welford_online"
harness = false
